AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SF worflow - Lambda Orchestration Automated Provision Resource


# # More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: python3.11
    MemorySize: 128
    CodeUri: "functions/"
    Timeout: 30
    Tracing: Active
  Api:
    TracingEnabled: true

Parameters:
  ResourcePrefix:
    Type: String
    Default: "sample-sfn-orchestrate-lambda"

    
Resources:
  SfnToJsonParsingFnConnector:
    Type: AWS::Serverless::Connector # More info about Connector Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-connector.html
    Properties:
      Source:
        Id: AutoProvisionStateMachine
      Destination:
        Id: JsonParsingFn
      Permissions:
      - Write

  SfnToApprovalStageFnConnector:
    Type: AWS::Serverless::Connector # More info about Connector Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-connector.html
    Properties:
      Source:
        Id: AutoProvisionStateMachine
      Destination:
        Id: ApprovalStageFn
      Permissions:
      - Write

  SfnToResourceProvisionFnConnector:
    Type: AWS::Serverless::Connector # More info about Connector Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-connector.html
    Properties:
      Source:
        Id: AutoProvisionStateMachine
      Destination:
        Id: ResourceProvisionFn
      Permissions:
      - Write
  SfnToValidationAndTestingFnConnector:
    Type: AWS::Serverless::Connector # More info about Connector Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-connector.html
    Properties:
      Source:
        Id: AutoProvisionStateMachine
      Destination:
        Id: ValidationAndTestingFn
      Permissions:
      - Write

# Delcare StateMachine under Resources
  AutoProvisionStateMachine:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      DefinitionUri: statemachine/statemachine.asl.json
      DefinitionSubstitutions:
        JsonParsingFnArn: !GetAtt JsonParsingFn.Arn
        ApprovalStageFnArn: !GetAtt ApprovalStageFn.Arn
        ResourceProvisionFnArn: !GetAtt ResourceProvisionFn.Arn
        ValidationAndTestingFnArn: !GetAtt ValidationAndTestingFn.Arn
      Policies:
      - CloudWatchPutMetricPolicy: {}


# Explicitly create all Lambda function log groups in order to:
#  * Set custom retention
#  * Allow automatic cleanup

  JsonParsingLog:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 1
      LogGroupName: !Sub "/aws/lambda/${ResourcePrefix}-json-parsing-stage-05-fn"
  
  ApprovalStageLog:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 1
      LogGroupName: !Sub "/aws/lambda/${ResourcePrefix}-approval-stage-06-fn"

  ResourceProvisionLog:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 1
      LogGroupName: !Sub "/aws/lambda/${ResourcePrefix}-resource-provision-stage-07-fn"
  
  ValidationAndTestingLog:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 1
      LogGroupName: !Sub "/aws/lambda/${ResourcePrefix}-validation-and-testing-stage-08-fn"

# Create all Lambda functions 
## Under the folder /functions Lambda
  JsonParsingFn:
    Type: AWS::Serverless::Function
    Properties:
      Handler: json-parsing-stage-05.handler
      Description: "Parsing json file content"
      FunctionName: !Sub "${ResourcePrefix}-json-parsing-stage-05-fn"

  ApprovalStageFn:
    Type: AWS::Serverless::Function
    Properties:
      Handler: approval-stage-06.handler
      Description: "Automated or Manual ApprovalStage"
      FunctionName: !Sub "${ResourcePrefix}-approval-stage-06-fn"
    DependsOn: [ApprovalStageLog]

  ResourceProvisionFn:
    Type: AWS::Serverless::Function
    Properties:
      Handler: resource-provision-stage-07.handler
      Description: "Provision Resource by template"
      FunctionName: !Sub "${ResourcePrefix}-resource-provision-stage-07-fn"
    DependsOn: [ResourceProvisionLog]

  ValidationAndTestingFn:
    Type: AWS::Serverless::Function
    Properties:
      Handler: validation-and-testing-stage-08.handler
      Description: "ValidationAndTesting"
      FunctionName: !Sub "${ResourcePrefix}-validation-and-testing-stage-08-fn"
    DependsOn: [ValidationAndTestingLog]  

  # Using App resource group for Monitoring
  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'

Outputs:
  # StockTradingStateMachineHourlyTradingSchedule is an implicit Schedule event rule created out of Events key under Serverless::StateMachine
  # Find out more about other implicit resources you can reference within SAM
  # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-generated-resources.html
  AutoProvisionStateMachineArn:
    Description:  State machine ARN
    Value: !Ref AutoProvisionStateMachine
  AutoProvisionStateMachineRoleArn:
    Description: IAM Role created for State machine based on the specified
      SAM Policy Templates
    Value: !GetAtt AutoProvisionStateMachineRole.Arn

