version = 0.1
[default.deploy.parameters]
stack_name = "creation-stack-v1"
resolve_s3 = true
s3_prefix = "creation-stack-v1"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "ResourcePrefix=\"sample-sfn-orchestrate-lambda\""
image_repositories = []
