AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SF worflow - Lambda Orchestration Automated Provision Create stack Resource


# # More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: python3.11
    MemorySize: 128
    CodeUri: "functions/"
    Timeout: 30
    Tracing: Active
  Api:
    TracingEnabled: true

Parameters:
  ResourcePrefix:
    Type: String
    Default: "sfn-orchestrate-lambda-stack-creation"


Resources:
#  Step function state machine IAM Role   
  SFRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "states.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: SFPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'cloudformation:CreateStack'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'xray:PutTraceSegments'
                  - 'xray:PutTelemetryRecords'
                  - 'xray:GetSamplingRules'
                  - 'xray:GetSamplingTargets'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'cloudformation:*'
                  - 'iam:*'
                  - 'lambda:*'
                  - 'apigateway:*'
                  - 's3:*'
                  - 'ecr:*'
                  - 'logs:*'
                  - 'cloudwatch:*' 
                  - 'dynamodb:*'
                  - 'tag:*'  
                  - 'resource-groups:*' # Allow creating ResourceGroups
                  - 'cloudfront:*'
                  - 'applicationinsights:*'  # Allow creating Application Insights Applications
                Resource: '*'

# Delcare StateMachine under Resources
  StackCreationStateMachine:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      DefinitionUri: statemachine/statemachine.asl.json
      Role: !GetAtt SFRole.Arn


# Explicitly create all Lambda function log groups in order to:
#  * Set custom retention
#  * Allow automatic cleanup
  CreationStackLog:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 1
      LogGroupName: !Sub "/aws/lambda/${ResourcePrefix}-creation-stack-fn"


# Create all Lambda functions 
## Under the folder /functions Lambda

  CreationStackFn:
    Type: AWS::Serverless::Function
    Properties:
      Handler: nothing.handler
      Description: "Automated or Manual ApprovalStage"
      FunctionName: !Sub "${ResourcePrefix}-creation-stack-fn"
      Policies:
      # Give the Lambda service access to poll your S3/ Container Stream
      - AmazonS3FullAccess
      - AmazonEC2ContainerRegistryFullAccess
    DependsOn: [CreationStackLog]



  # Using App resource group for Monitoring
  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'

Outputs:
  # Find out more about other implicit resources you can reference within SAM
  # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-generated-resources.html
  StackCreationStateMachineArn:
    Description:  State machine ARN
    Value: !Ref StackCreationStateMachine
