AWSTemplateFormatVersion: '2010-09-09'
Resources:
  CreationStackFnCustomIAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: CreationStackFnCustomIAMRole 
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - states.amazonaws.com 
            Action: 'sts:AssumeRole'
  MyIAMPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: MyPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 'cloudformation:CreateStack'
            Resource: '*'
          - Effect: Allow
            Action:
              - 'xray:PutTraceSegments'
              - 'xray:PutTelemetryRecords'
              - 'xray:GetSamplingRules'
              - 'xray:GetSamplingTargets'
            Resource: '*'
          - Effect: Allow
            Action:
              - 'cloudformation:*'
              - 'iam:*'
              - 'lambda:*'
              - 'apigateway:*'
              - 's3:*'
              - 'ecr:*'
              - 'logs:*'
            Resource: '*'
      Roles:
        - !Ref CreationStackFnCustomIAMRole # Reference the CreationStackFnCustomIAMRole here
